<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2yc.idR' shared service.

return $this->privates['.service_locator.2yc.idR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.2yc.idR.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.2yc.idR": it references class "App\\Entity\\Users" but no such service exists.'],
]);
