<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8z1HQm8' shared service.

return $this->privates['.service_locator.8z1HQm8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'group' => ['privates', '.errored..service_locator.8z1HQm8.App\\Entity\\Groups', NULL, 'Cannot autowire service ".service_locator.8z1HQm8": it references class "App\\Entity\\Groups" but no such service exists.'],
]);
