<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dnczLyX' shared service.

return $this->privates['.service_locator.dnczLyX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'zone' => ['privates', '.errored..service_locator.dnczLyX.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.dnczLyX": it references class "App\\Entity\\Zone" but no such service exists.'],
]);
