<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.alodU2Q' shared service.

return $this->privates['.service_locator.alodU2Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'address' => ['privates', '.errored..service_locator.alodU2Q.App\\Entity\\Addresses', NULL, 'Cannot autowire service ".service_locator.alodU2Q": it references class "App\\Entity\\Addresses" but no such service exists.'],
]);
