<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.m08Htcr' shared service.

return $this->privates['.service_locator.m08Htcr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'enquiry' => ['privates', '.errored..service_locator.m08Htcr.App\\Entity\\Enquiry', NULL, 'Cannot autowire service ".service_locator.m08Htcr": it references class "App\\Entity\\Enquiry" but no such service exists.'],
]);
