<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AddressesController::delete' => ['privates', '.service_locator.alodU2Q', 'get_ServiceLocator_AlodU2QService.php', true],
    'App\\Controller\\AddressesController::edit' => ['privates', '.service_locator.alodU2Q', 'get_ServiceLocator_AlodU2QService.php', true],
    'App\\Controller\\AddressesController::show' => ['privates', '.service_locator.alodU2Q', 'get_ServiceLocator_AlodU2QService.php', true],
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\EnquiryController::delete' => ['privates', '.service_locator.m08Htcr', 'get_ServiceLocator_M08HtcrService.php', true],
    'App\\Controller\\EnquiryController::edit' => ['privates', '.service_locator.m08Htcr', 'get_ServiceLocator_M08HtcrService.php', true],
    'App\\Controller\\EnquiryController::show' => ['privates', '.service_locator.m08Htcr', 'get_ServiceLocator_M08HtcrService.php', true],
    'App\\Controller\\GroupsController::delete' => ['privates', '.service_locator.8z1HQm8', 'get_ServiceLocator_8z1HQm8Service.php', true],
    'App\\Controller\\GroupsController::edit' => ['privates', '.service_locator.8z1HQm8', 'get_ServiceLocator_8z1HQm8Service.php', true],
    'App\\Controller\\GroupsController::show' => ['privates', '.service_locator.8z1HQm8', 'get_ServiceLocator_8z1HQm8Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\ServiceController::delete' => ['privates', '.service_locator..7DLMsk', 'get_ServiceLocator__7DLMskService.php', true],
    'App\\Controller\\ServiceController::edit' => ['privates', '.service_locator..7DLMsk', 'get_ServiceLocator__7DLMskService.php', true],
    'App\\Controller\\ServiceController::show' => ['privates', '.service_locator..7DLMsk', 'get_ServiceLocator__7DLMskService.php', true],
    'App\\Controller\\UsersController::delete' => ['privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true],
    'App\\Controller\\UsersController::edit' => ['privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true],
    'App\\Controller\\UsersController::show' => ['privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true],
    'App\\Controller\\ZoneController::delete' => ['privates', '.service_locator.dnczLyX', 'get_ServiceLocator_DnczLyXService.php', true],
    'App\\Controller\\ZoneController::edit' => ['privates', '.service_locator.dnczLyX', 'get_ServiceLocator_DnczLyXService.php', true],
    'App\\Controller\\ZoneController::show' => ['privates', '.service_locator.dnczLyX', 'get_ServiceLocator_DnczLyXService.php', true],
    'App\\Controller\\AddressesController:delete' => ['privates', '.service_locator.alodU2Q', 'get_ServiceLocator_AlodU2QService.php', true],
    'App\\Controller\\AddressesController:edit' => ['privates', '.service_locator.alodU2Q', 'get_ServiceLocator_AlodU2QService.php', true],
    'App\\Controller\\AddressesController:show' => ['privates', '.service_locator.alodU2Q', 'get_ServiceLocator_AlodU2QService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\EnquiryController:delete' => ['privates', '.service_locator.m08Htcr', 'get_ServiceLocator_M08HtcrService.php', true],
    'App\\Controller\\EnquiryController:edit' => ['privates', '.service_locator.m08Htcr', 'get_ServiceLocator_M08HtcrService.php', true],
    'App\\Controller\\EnquiryController:show' => ['privates', '.service_locator.m08Htcr', 'get_ServiceLocator_M08HtcrService.php', true],
    'App\\Controller\\GroupsController:delete' => ['privates', '.service_locator.8z1HQm8', 'get_ServiceLocator_8z1HQm8Service.php', true],
    'App\\Controller\\GroupsController:edit' => ['privates', '.service_locator.8z1HQm8', 'get_ServiceLocator_8z1HQm8Service.php', true],
    'App\\Controller\\GroupsController:show' => ['privates', '.service_locator.8z1HQm8', 'get_ServiceLocator_8z1HQm8Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\ServiceController:delete' => ['privates', '.service_locator..7DLMsk', 'get_ServiceLocator__7DLMskService.php', true],
    'App\\Controller\\ServiceController:edit' => ['privates', '.service_locator..7DLMsk', 'get_ServiceLocator__7DLMskService.php', true],
    'App\\Controller\\ServiceController:show' => ['privates', '.service_locator..7DLMsk', 'get_ServiceLocator__7DLMskService.php', true],
    'App\\Controller\\UsersController:delete' => ['privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true],
    'App\\Controller\\UsersController:edit' => ['privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true],
    'App\\Controller\\UsersController:show' => ['privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true],
    'App\\Controller\\ZoneController:delete' => ['privates', '.service_locator.dnczLyX', 'get_ServiceLocator_DnczLyXService.php', true],
    'App\\Controller\\ZoneController:edit' => ['privates', '.service_locator.dnczLyX', 'get_ServiceLocator_DnczLyXService.php', true],
    'App\\Controller\\ZoneController:show' => ['privates', '.service_locator.dnczLyX', 'get_ServiceLocator_DnczLyXService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
