<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9DsgKiY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9DsgKiY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9DsgKiY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9DsgKiY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9DsgKiY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9DsgKiY',
    'container.build_id' => '4f5947c7',
    'container.build_time' => 1558531392,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9DsgKiY');
