<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2YJyXx4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2YJyXx4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2YJyXx4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2YJyXx4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2YJyXx4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2YJyXx4',
    'container.build_id' => '906d67be',
    'container.build_time' => 1558336215,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2YJyXx4');
