<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATb19mr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATb19mr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATb19mr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATb19mr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerATb19mr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ATb19mr',
    'container.build_id' => 'e3ef1bf9',
    'container.build_time' => 1558958141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATb19mr');
